name: "游댮 Bug"
description: "Reportar um defeito ou comportamento inesperado"
labels: ["type:bug", "priority:p1"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Descreva o problema de forma clara para facilitar a corre칞칚o.

  - type: textarea
    id: description
    attributes:
      label: Descri칞칚o do Bug
      description: O que est치 acontecendo de errado?
      placeholder: "O bot칚o de login n칚o responde quando clicado"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Como reproduzir o bug?
      placeholder: |
        1. Acesse a p치gina de login
        2. Digite email e senha
        3. Clique em "Entrar"
        4. Observe que nada acontece
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria acontecer?
      placeholder: "Deveria fazer login e redirecionar para o dashboard"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que est치 acontecendo?
      placeholder: "O bot칚o fica em loading infinito"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      description: Qual o impacto desse bug?
      options:
        - "P0-Critical: Sistema inutiliz치vel"
        - "P1-High: Feature importante quebrada"
        - "P2-Medium: Funciona com workaround"
        - "P3-Low: Cosm칠tico ou edge case"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: Onde acontece?
      placeholder: "Chrome 120, macOS, Produ칞칚o"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Console errors, screenshots, etc
      placeholder: "Cole aqui ou anexe imagens"
    validations:
      required: false

  - type: input
    id: workaround
    attributes:
      label: Workaround (se houver)
      description: Existe alguma forma de contornar?
      placeholder: "Recarregar a p치gina funciona"
    validations:
      required: false
